composer追加

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -22,3 +22,22 @@ RUN apt-get install -y libonig-dev
 RUN docker-php-ext-install pdo_pgsql
 RUN docker-php-ext-install mbstring
 
+RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+RUN ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+RUN if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; \
+    then \
+        >&2 echo 'ERROR: Invalid installer signature'; \
+        rm composer-setup.php; \
+        exit 1; \
+    fi;
+
+RUN php composer-setup.php --quiet
+RUN RESULT=$?
+
+RUN mv composer.phar /usr/local/bin/composer
+RUN rm composer-setup.php
+RUN exit $RESULT
+
+ENV COMPOSER_ALLOW_SUPERUSER 1
+ENV PATH $PATH:/composer/vendor/bin
